development:
  adapter: postgresql
  encoding: unicode
  database: vagrant
  pool: 5
  username: vagrant
  password: vagrant
test:
  adapter: postgresql
  encoding: unicode
  database: test
  pool: 5
  username: vagrant
  password: vagrant
production:
  adapter: postgresql
  encoding: unicode
  pool: 1
  database: dd3dru0ot5eop9
  username: bnvghttnvtklig
  password: cMdpSW9agLb4HEBOlh-Th9x4Jx
  host: ec2-107-21-100-118.compute-1.amazonaws.com
  port: 5432
