development:
  adapter: postgresql
  encoding: unicode
  database: vagrant
  pool: 5
  username: vagrant
  password: vagrant
test:
  adapter: postgresql
  encoding: unicode
  database: test
  pool: 5
  username: vagrant
  password: vagrant
production:
  adapter: postgresql
  encoding: unicode
  database: myapp_production
  pool: 5
  username: myapp
  password:
